apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    # app.kubernetes.io/name: learn_kubernetes
    event : kubernetes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000